version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/run
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 100
      runas: root
