version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  AfterInstall:
    - location: post_install
      timeout: 100
      runas: root
  ApplicationStart:
    - location: run
      timeout: 100
      runas: root
