#!/usr/bin/env bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

. ~/.nvm/nvm.sh

nvm install node

node -e "console.log('Running Node.js ' + process.version)"
cd /tmp/

curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
yum install -y nodejs
yum install -y npm
